---
.gitignore:
  required:
    - ---.project

.travis.yml:
  unmanaged: true

Gemfile:
  required:
    ':system_tests':
      - gem: 'puppet-module-posix-system-r#{minor_version}'
        platforms: ruby
      - gem: 'puppet-module-win-system-r#{minor_version}'
        platforms:
          - mswin
          - mingw
          - x64_mingw
      - gem: beaker-testmode_switcher
    ':development':
      - gem: 'net-ssh'
        version: '< 5.0.0'
      - gem: 'puppet-lint-i18n'
      - gem: 'puppet_litmus'
        git: 'https://github.com/puppetlabs/puppet_litmus.git'
      - gem: 'pdk'
        git: 'https://github.com/tphoney/pdk.git'
        branch: 'pin_cri'
      - gem: 'serverspec'
  optional:
    ':development':
      - gem: 'github_changelog_generator'
        git: 'https://github.com/skywinder/github-changelog-generator'
        ref: '20ee04ba1234e9e83eb2ffb5056e23d641c7a018'
        condition: "Gem::Version.new(RUBY_VERSION.dup) >= Gem::Version.new('2.2.2')"

appveyor.yml:
  unmanaged: true

Rakefile:
  requires:
    - puppet_pot_generator/rake_tasks
  use_litmus_tasks: true
  changelog_user: 'puppetlabs'

spec/spec_helper.rb:
  spec_overrides:
    -  "require 'spec_helper_local'"

.rubocop.yml:
   default_configs:
    inherit_from: .rubocop_todo.yml
    require:
      - rubocop-i18n
      - rubocop-rspec

.gitlab-ci.yml:
  unmanaged: true
