---
sudo: false
dist: trusty
language: ruby
cache: bundler
  - rm -f Gemfile.lock
  - gem update --system
  - gem --version
  - bundle -v
script:
  - 'bundle exec rake $CHECK'
bundler_args: --without system_tests
rvm:
  - 2.5.1
env:
  global:
    - PUPPET6=debian9 PUPPET_GEM_VERSION="~> 6.0"
matrix:
  fast_finish: true
  include:
    -
      bundler_args:
      dist: trusty
      env: PUPPET6=debian:8_9
      script:
      - install: travis_wait 40 mvn install
      - bundle exec rake 'litmus:provision[docker, waffleimage/debian8]'
      - bundle exec rake 'litmus:provision[docker, waffleimage/debian9]'
      - bundle exec bolt command run 'apt-get install wget -y' --inventoryfile inventory.yaml --nodes='localhost*'
      - bundle exec rake litmus:install_agent
      - bundle exec rake litmus:install_module
      - bundle exec rake litmus:acceptance:parallel
      services: docker
      sudo: required
    -
      env: CHECK="syntax lint metadata_lint check:symlinks check:git_ignore check:dot_underscore check:test_file rubocop"
    -
      env: CHECK=parallel_spec
    -
      env: PUPPET_GEM_VERSION="~> 5.0" CHECK=parallel_spec
      rvm: 2.4.4
    -
      bundler_args:
      dist: trusty
      env: PUPPET5=debian:8_9
      script:
      - install: travis_wait 40 mvn install
      - bundle exec rake 'litmus:provision[docker, waffleimage/debian8]'
      - bundle exec rake 'litmus:provision[docker, waffleimage/debian9]'
      - bundle exec bolt command run 'apt-get install wget -y' --inventoryfile inventory.yaml --nodes='localhost*'
      - bundle exec rake 'litmus:install_agent[puppet5]'
      - bundle exec rake litmus:install_module
      - bundle exec rake litmus:acceptance:parallel
      services: docker
      sudo: required
    -
      bundler_args:
      dist: trusty
      env: PUPPET5=centos:6_7
      script:
      - install: travis_wait 40 mvn install
      - bundle exec rake 'litmus:provision[docker, waffleimage/centos6]'
      - bundle exec rake 'litmus:provision[docker, waffleimage/centos7]'
      - bundle exec bolt command run 'apt-get install wget -y' --inventoryfile inventory.yaml --nodes='localhost*'
      - bundle exec rake 'litmus:install_agent[puppet5]'
      - bundle exec rake litmus:install_module
      - bundle exec rake litmus:acceptance:parallel
      services: docker
      sudo: required
branches:
  only:
    - master
    - /^v\d/
    - release
notifications:
  email: false
deploy:
  provider: puppetforge
  user: puppet
  password:
    secure: ""
  on:
    tags: true
    all_branches: true
    condition: "$DEPLOY_TO_FORGE = yes"
